src/legend_data.jl
Added string number, string position, HV card, DAQ card and CC4 card to the channel info creator to have more values accessible for sorting detectors. Especially useful if you want e.g. to investigate just one string, build visualization maps or look into specific electronic cards and their effects on the detectors. Screenshot shows example table:
@oschulz The naming of the columns in the table can changed. This is just my proposal.
=> More values in channel info

src/props_db.jl
Enables
```julia
julia> pd.no.such.props.yet isa LegendDataManagement.NoSuchPropsDBEntry
true
julia> writeprops(pd.no.such.props.yet, PropDict("foo" => 42))
julia> pd.no.such.props.yet isa PropDict
true
```
=> Add NoSuchPropsDBEntry

src/legend_data.jl, test/test_legend_data.jl
The usability key in the metadata has different meaning and treating it static as `"on" = true` is not enough since some channels have `no_psd` and `ac` and have to be processed anyhow. Changed this field to be a Symbol so that different selections can be performed.
=> Change Usability Key

src/LegendDataManagement.jl, src/dataprod_config.jl, src/filekey.jl, src/legend_data.jl
Added functionality which was so far in the dataflow:
- `is_analysis_run` checks if the run is a analysis run
- `start_key` returns the starting FileKey for a given period and run
- `phy_livetime` returns the livetime for a given run and period
Also, I extended the `channelinfo` to be able to get the info for a given run and period by using the `start_key` as a reference and also to get a handy access to the `:geds` subsytem with 
``` julia
channelinfo(l200, (:p03, :r000, :cal))
channelinfo(l200, (:p03, :r000, :cal); system=:geds, processable=true)
```
This makes this whole process of getting filekeys etc way more handy and the user can just get the `channelinfo` for a given run much more human readable.
I will also move some of the `addprocs` functionality and try to start with some of …
=> Processing updates

src/data_config.jl
The tests on Windows keep on failing since implementing the support for colon-separated filenames in `LEGEND_DATA_CONFIG` in commit https://github.com/legend-exp/LegendDataManagement.jl/commit/80b0c1182433693b4a298ee8670f8f9d933ba99a.
What happens is that `LEGEND_DATA_CONFIG` is split at every colon, including the colons that might belong to a Windows file path (`C:\\...`). In this PR, I replaced the simple `':'` as the split condition with a regular expression `r":(?!\\)` to avoid splitting `:\\` as expected in Windows file paths.
I hope that the tests on Windows will pass again with this fix.
=> Bugfix in parsing `LegendDataConfig` on Windows

src/filekey.jl, src/legend_report.jl
Need to be able to pass DataSelectors and round numbers automatically to have cleaner reports.
Rounding is temp and can be removed, but I would still merge to have a stable release now for all the data production since I am already using that actively.
=> LegendReport can talk with DataSelectors and rounds numbers

src/filekey.jl
This PR addresses the changes in commit 57c3eb1b96c5034d020013bedb60b93bdff0db29.
Seems like there are two kinds of `ChannelIds`: one with three digits (old) and one with seven digits (new).
The implementation of how to check the validity of a `ChannelId` seemed a bit buggy.
I tried to fix it but would need some feedback from people who have worked with `ChannelIds` more.
My understanding:
- a 3-digit `ChannelId` can be anything from 0 (or 1?) to 999.
- a 7-digit `ChannelId` cannot have the first two digits being BOTH 0, otherwise they can be whatever.
If this is true, I updated the regular expression `ch_expr`.
I also updated the code to add leading zeros to `Integers` before being checked for validity.
This might prevent the current tests from failing.
=> Fixes in `ChannelId` parsing

.github/workflows/CompatHelper.yml, .github/workflows/DocPreviewCleanup.yml, .github/workflows/TagBot.yml, .github/workflows/ci.yml, Project.toml, src/LegendDataManagement.jl, src/active_volume.jl, src/legend_data.jl, test/test_ext_ssd.jl, test/test_legend_data.jl
`channelinfo` now has a new keyword: `detailed` (can also be renamed to something else) with default value `false`.
If set to `true`, the function `channelinfo` will calculate the total volume and the active volume of all `:geds` based on the FCCD values provided in the metadata and adds them as columns to the output of `channelinfo`.
There are warnings for:
- detectors with `cracks` in the metadata (the functions to calculate their volumes are still missing)
- detectors with no FCCD values provided (there, the active volume is equal to the total volume)
=> Active and total volume calculation

src/active_volume.jl, src/legend_data.jl
Currently, the active volume calculation for detectors with cracks was not implemented.
I did the calculation and added the formulas for vertical and inclined cracks to the code.
The only thing missing is the handling of `fccd`, 
@fhagemann: could you add this?
=> Implement active volume calculation for cracks

src/legend_data.jl, src/props_db.jl, test/test_legend_data.jl
Override data locations are
```
/path/to/metadata/jldataprod/overrides/metadata/...
/path/to/metadata/jldataprod/overrides/par/...
/path/to/metadata/jldataprod/overrides/jlpar/...
```
@theHenks can you test if this PR works for you?
=> Add PropsDB overrides

src/ljl_expressions.jl, test/test_ljl_expressions.jl
Also add support for square-brackets index access, the conditional ternary operator and functions `one`, `zero` and `identity`.
=> Support dot-based getproperty in ljl_propfunc

src/utils/pars_utils.jl, src/utils/utils.jl
Fixed import of `Distributed` for validity creation.
=> Bug fix `write_validity`

Project.toml, src/LegendDataManagement.jl, src/lprops.jl
To properly parse units with e.g. special units from `UnitfulAtomic`, the function `unit_from_string` from `LegendDataTypes` is now used to avoid that.
=> Bug fix `lprops`

src/dataprod_config.jl, src/exposure.jl, src/utils/management_utils.jl, src/utils/pars_utils.jl
`partitioninfo` allows to filter for `analysis_runs` only to be able to parse `:phy` and `:cal`
=> Allow `partitioninfo` to filter categories

docs/src/extensions.md, ext/LegendDataManagementLegendHDF5IOExt.jl
Included `ignore_missing` kwarg in `read_ldata` to be able to ignore missing channels. In particular useful for Water Cherenkov PMT analysis.
``` julia
raw = read_ldata(l200, DataTier(:raw), :phy, :p03, :r000, ch; ignore_missing=true)
```
=> Bug Fix `read_ldata`

src/legend_data.jl, test/Project.toml, test/test_legend_data.jl
Alternative to #80 (which can be used once https://github.com/legend-exp/legend-detectors/pull/48 is merged and according dummy values are added to legend-testdata).
I am not sure if `Measurements` can deal with asymmetric errors, so right now I'm estimating the uncertainty as the maximum number quoted as `uncertainty` in the metadata (`pos` and `neg`).
=> Add uncertainties for active volume calculation

src/calibration_functions.jl
This PR includes the `LQ` calibration functions and `PSD` classifier defintions:
- `LQ` calibration and cut definition
- `psd_classifier` propfunc
**Attention**: This PR inverts the `A/E` and `LQ` cut logic: Any `classifier_cut` parameter is now `true` if the event should be cut. This makes the `PSD` part consisten with the rest of the `jlevt` level.
**Note**: This PR only works in combination with [PR#14](https://github.com/legend-exp/LegendEventAnalysis.jl/pull/14) in `LegendEventAnalysis`
=> `LQ` calibration functions and `PSD` propfuncs

src/legend_data.jl
`search_disk` is failing for `search_disk(DataSet)` if the `_cashed_dataset` does not exist
=> Bug Fix `search_disk`

src/calibration_functions.jl, src/evt_functions.jl
This PR includes `jlevt` and calibration functions for the `PMT` veto system. In addition, the `is_physical_trig` propfunc is generated.
**Note**: This PR only works in combination with [PR#16](https://github.com/legend-exp/LegendEventAnalysis.jl/pull/16) in `LegendEventAnalysis`
=> `PMT` calibration + event level functions 

src/legend_data.jl
This PR includes the `psd_usability` according to the _pygama_ layout of the `psd_status`
=> Include `psd_usability` in `channelinfo`

ext/LegendDataManagementLegendHDF5IOExt.jl
Looks like we are using a deprecated method for `TypesTable.getproperties` in our package:
https://github.com/JuliaData/TypedTables.jl/blob/702cf7fdde8d6ac9822c8f43d695b50f6b183508/src/properties.jl#L87
I did not test whether this still works, but it's throwing deprecation warnings in tests.
=> Avoid using deprecated method for `getproperties`

ext/LegendDataManagementSolidStateDetectorsExt.jl, test/test_ext_ssd.jl
Some things got a bit mixed up in #91.
For example
```julia
l200 = LegendData(:l200)
sim = Simulation(l200, :V00050A)
```
seemed to work in the past but doesn't now. It explicitly requires a precision type in curly brackets:
```julia
sim = Simulation{T}(l200, :V00050A)
```
This should be fixed with this PR.
=> Add more methods to create SSD objects from metadata

docs/src/extensions.md, ext/LegendDataManagementLegendHDF5IOExt.jl, test/test_legend_data.jl
This PR allows the use of `read_ldata` to read multiple files in parallel. The function `read_ldata` is extended by two additional `kwargs`:
- `parallel`: read files in parallel, default `false`
- `wpool`: worker pool to use for parallel read, only applies if `parallel = true`, default `default_worker_pool()` containing all workers 
The function automatically parallels all runs, periods and files for maximum speed.
=> Parallel `read_ldata`

src/calibration_functions.jl
Renamed LQ `cut` --> `highcut` to deal with new dataflow update. 
This PR belongs to [PR#92](https://github.com/legend-exp/legend-julia-dataflow/pull/92) in `legend-julia-dataflow` to streamline the `LQ` naming convention with the other PSD parameters
=> Rename LQ `highcut`

src/props_db.jl
This PR allows the `PropsDB` to use properties from overrides paths even in the case when there are no props existing under th `_base_path`. This is in particluar useful for `jlpars` which are disitrbuted via the `jldataprod-overrides` repository and not generated within the `dataflow`
=> Patch `PropsDB` overrides

docs/src/extensions.md
The instructions written on the extension section of LegendDataManagement did not work for me when I attempted to simulate the electric field and weighting potential of a detector. I had to tweak some parts of the code to get it working. So, I just wanted to open up a discussion about this!
=> Updating the documentation for simulating the electric field and weighting potential of a given detector

src/data_config.jl, src/dataprod_config.jl, src/legend_data.jl, test/test_legend_data.jl
I added the discussed functionality to add a dataset to the legend-data-config.
SetupConfig has the field `dataset` that is read from the config file. If no dataset is specified, it defaults to `:valid` as dataset. 
The config dataset can be overwritten during the construction of the LegenData struct by:
`LegendData(:setup ; dataset =  :new_dataset)`
@oschulz is this implementation fine like this?
With this added I changed the `analysis_runs` function to use the dataset specified in LegenData for the used runlist to check for analysis runs.
In the actual runinfo i did not change anything, as I understood the runinfo should always print all general available runs.
Just the is_ana_run is now dependent on the dataset.
I added a test, to check if the overwriting works properly. They are …
=> add dataset to LegendData and SetupConfig struct
